# Ways to Get Data from/through the Internet

## Best - Backend API
- structured calls (intended by dev)
- good for us because we get (usually) useful, clean-ish data
- good for dev bc they have more control over what data we get

## Second Best (though usually much worse) - Frontend Webscraping
- generally loop through code rather than single call
- frontend usually not as carefully structured as backend
- dev has little control over requests
- frontends change much more likely and rapidly than backend, can cause web scrapers to break

## Usually worst option by far - regex
- "I have to solve a problem with regex. Now I have two problems."

# Web Scrapping Example - Old Way

In [21]:
import urllib.request
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd

In [22]:
source = urllib.request.urlopen('https://www.basketball-reference.com/teams/MEM/2022.html').read()

In [23]:
soup = BeautifulSoup(source, 'html')

In [24]:
table = soup.find_all('table')[1]

In [25]:
roster_html = soup.find(id='roster')

# Web Scrapping Example - Pandas

In [27]:
# read into DataFrame
roster = pd.read_html(str(roster_html))[0]
roster

,No.,Player,Pos,Ht,Wt,Birth Date,Unnamed: 6,Exp,College
0,13,Jaren Jackson Jr.,PF,6-11,242,"September 15, 1999",us,3,Michigan State
1,22,Desmond Bane,SF,6-5,215,"June 25, 1998",us,1,TCU
2,4,Steven Adams,C,6-11,265,"July 20, 1993",nz,8,Pitt
3,0,De'Anthony Melton,SG,6-2,200,"May 28, 1998",us,3,USC
4,21,Tyus Jones,PG,6-0,196,"May 10, 1996",us,6,Duke
5,46,John Konchar,SG,6-5,210,"March 22, 1996",us,2,Purdue-Fort Wayne
6,1,Kyle Anderson,PF,6-9,230,"September 20, 1993",us,7,UCLA
7,15,Brandon Clarke,PF,6-8,215,"September 19, 1996",ca,2,"San Jose State, Gonzaga"
8,8,Ziaire Williams,SF,6-8,215,"September 12, 2001",us,R,Stanford
9,12,Ja Morant,PG,6-3,174,"August 10, 1999",us,2,Murray State
10,2,Xavier Tillman Sr.,PF,6-8,245,"January 12, 1999",us,1,Michigan State
11,23,Jarrett Culver,SG,6-6,195,"February 20, 1999",us,2,Texas Tech
12,35,Killian Tillie,C,6-9,220,"March 5, 1998",fr,1,Gonzaga
13,24,Dillon Brooks,SF,6-7,225,"January 22, 1996",ca,4,Oregon
14,7,Santi Aldama,PF,6-11,224,"January 10, 2001",es,R,Loyola (MD)
15,5,Yves Pons (TW),SF,6-6,215,"May 7, 1999",ht,R,Tennessee
16,25,Sam Merrill,SG,6-4,205,"May 15, 1996",us,1,Utah State University
17,3,Tyrell Terry (TW),PG,6-2,160,"September 28, 2000",us,1,Stanford

In [31]:
roster_old_way = soup.find_all('table')[0]
roster_old_way
roster2 = pd.read_html(str(roster_old_way))
roster2[0]

,No.,Player,Pos,Ht,Wt,Birth Date,Unnamed: 6,Exp,College
0,13,Jaren Jackson Jr.,PF,6-11,242,"September 15, 1999",us,3,Michigan State
1,22,Desmond Bane,SF,6-5,215,"June 25, 1998",us,1,TCU
2,4,Steven Adams,C,6-11,265,"July 20, 1993",nz,8,Pitt
3,0,De'Anthony Melton,SG,6-2,200,"May 28, 1998",us,3,USC
4,21,Tyus Jones,PG,6-0,196,"May 10, 1996",us,6,Duke
5,46,John Konchar,SG,6-5,210,"March 22, 1996",us,2,Purdue-Fort Wayne
6,1,Kyle Anderson,PF,6-9,230,"September 20, 1993",us,7,UCLA
7,15,Brandon Clarke,PF,6-8,215,"September 19, 1996",ca,2,"San Jose State, Gonzaga"
8,8,Ziaire Williams,SF,6-8,215,"September 12, 2001",us,R,Stanford
9,12,Ja Morant,PG,6-3,174,"August 10, 1999",us,2,Murray State
10,2,Xavier Tillman Sr.,PF,6-8,245,"January 12, 1999",us,1,Michigan State
11,23,Jarrett Culver,SG,6-6,195,"February 20, 1999",us,2,Texas Tech
12,35,Killian Tillie,C,6-9,220,"March 5, 1998",fr,1,Gonzaga
13,24,Dillon Brooks,SF,6-7,225,"January 22, 1996",ca,4,Oregon
14,7,Santi Aldama,PF,6-11,224,"January 10, 2001",es,R,Loyola (MD)
15,5,Yves Pons (TW),SF,6-6,215,"May 7, 1999",ht,R,Tennessee
16,25,Sam Merrill,SG,6-4,205,"May 15, 1996",us,1,Utah State University
17,3,Tyrell Terry (TW),PG,6-2,160,"September 28, 2000",us,1,Stanford

# Can also do it locally ... instead of spamming urls

In [32]:
import pandas as pd
from bs4 import BeautifulSoup

In [33]:
html_file = "downloaded html file"

with open(html_file, 'rb') as f:
    soup = BeautifulSoup(f, 'lxml')

FileNotFoundError: [Errno 2] No such file or directory: 'downloaded html file'

In [34]:
roster_html = soup.find(id='roster')
roster = pd.read_html(str(roster_html))[0]
roster

,No.,Player,Pos,Ht,Wt,Birth Date,Unnamed: 6,Exp,College
0,13,Jaren Jackson Jr.,PF,6-11,242,"September 15, 1999",us,3,Michigan State
1,22,Desmond Bane,SF,6-5,215,"June 25, 1998",us,1,TCU
2,4,Steven Adams,C,6-11,265,"July 20, 1993",nz,8,Pitt
3,0,De'Anthony Melton,SG,6-2,200,"May 28, 1998",us,3,USC
4,21,Tyus Jones,PG,6-0,196,"May 10, 1996",us,6,Duke
5,46,John Konchar,SG,6-5,210,"March 22, 1996",us,2,Purdue-Fort Wayne
6,1,Kyle Anderson,PF,6-9,230,"September 20, 1993",us,7,UCLA
7,15,Brandon Clarke,PF,6-8,215,"September 19, 1996",ca,2,"San Jose State, Gonzaga"
8,8,Ziaire Williams,SF,6-8,215,"September 12, 2001",us,R,Stanford
9,12,Ja Morant,PG,6-3,174,"August 10, 1999",us,2,Murray State
10,2,Xavier Tillman Sr.,PF,6-8,245,"January 12, 1999",us,1,Michigan State
11,23,Jarrett Culver,SG,6-6,195,"February 20, 1999",us,2,Texas Tech
12,35,Killian Tillie,C,6-9,220,"March 5, 1998",fr,1,Gonzaga
13,24,Dillon Brooks,SF,6-7,225,"January 22, 1996",ca,4,Oregon
14,7,Santi Aldama,PF,6-11,224,"January 10, 2001",es,R,Loyola (MD)
15,5,Yves Pons (TW),SF,6-6,215,"May 7, 1999",ht,R,Tennessee
16,25,Sam Merrill,SG,6-4,205,"May 15, 1996",us,1,Utah State University
17,3,Tyrell Terry (TW),PG,6-2,160,"September 28, 2000",us,1,Stanford

# Reg expressions 
- Ton of exercises in textbook

# API Example

In [35]:
import pandas as pd
import urllib.request, urllib.parse
import json

In [36]:
api_url = 'https://www.thecocktaildb.com/api/json/v1/1/search.php?s=margarita'

uh = urllib.request.urlopen(api_url)

data = uh.read().decode()

In [39]:
drinks_json = json.loads(data)
drinks_df = pd.json_normalize(drinks_json['drinks'])
drinks_df

,idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,...,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified
0,11007,Margarita,None,"IBA,ContemporaryClassic",None,Ordinary Drink,Contemporary Classics,Alcoholic,Cocktail glass,Rub the rim of the glass with the lime slice t...,...,None,None,None,None,None,None,https://commons.wikimedia.org/wiki/File:Klassi...,Cocktailmarler,Yes,2015-08-18 14:42:59
1,11118,Blue Margarita,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,Rub rim of cocktail glass with lime juice. Dip...,...,None,None,None,None,None,None,None,None,Yes,2015-08-18 14:51:53
2,17216,Tommy's Margarita,None,"IBA,NewEra",None,Ordinary Drink,New Era Drinks,Alcoholic,Old-Fashioned glass,Shake and strain into a chilled cocktail glass.,...,None,None,None,None,None,None,None,None,No,2017-09-02 18:37:54
3,16158,Whitecap Margarita,None,None,None,Other/Unknown,None,Alcoholic,Margarita/Coupette glass,Place all ingredients in a blender and blend u...,...,None,None,None,None,None,None,None,None,No,2015-09-02 17:00:22
4,12322,Strawberry Margarita,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,Rub rim of cocktail glass with lemon juice and...,...,None,None,None,None,None,None,None,None,No,2015-08-18 14:41:51
5,178332,Smashed Watermelon Margarita,None,None,None,Cocktail,None,Alcoholic,Collins glass,In a mason jar muddle the watermelon and 5 min...,...,None,None,None,None,None,None,None,None,No,None